<div class="panel panel-primary">
    <div class="panel-heading">
       <div class="panel-title">
            Detalhes Usuário ID <?php echo $this->escapeHtml($this->id); ?>            
        </div>
    </div>
    <div class="panel-body">
        <dl class="dl-horizontal">
            <dt>Nome:</dt>
            <dd><?php echo $this->escapeHtml($this->form["nm_nom_usu"]); ?></dd>
            <dt>Nível de Login:</dt>
            <dd><?php echo $this->escapeHtml($this->form["nm_niv_usu"]); ?></dd>
            <dt>Usuário Ativo:</dt>
            <dd><?php echo $this->escapeHtml($this->form["nu_ati_usu"]); ?></dd>
            <dt>Data Criação:</dt>
            <dd><?php echo $this->escapeHtml($this->form["dt_cad_usu"]); ?></dd>
            <dt>Data Atualização:</dt>
            <dd><?php echo $this->escapeHtml($this->form["dt_ult_mov"]); ?></dd>
        </dl>
    </div>
    <div class="panel-footer">
        <a href="<?php echo $this->url('usuarios', array('action' => 'editar', 'id' => $this->id)); ?>" class="btn btn-warning btn-sm">Editar Usuário</a>
        <a href="<?php echo $this->url('usuarios'); ?>" class="btn btn-default btn-sm">Voltar</a>
    </div>
</div>