<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="panel-title">
            Editar Contato ID <?php echo $this->id; ?>        
        </div>
    </div>
    <form class="form-horizontal" role="form" method="POST" action="<?php echo $this->url('usuarios', array('action' => 'atualizar')); ?>">
        <div class="panel-body">
            <div class="form-group">
                <label for="inputNome" class="col-lg-3 col-md-3 control-label">Nome:</label>
                <div class="col-lg-9 col-md-9">
                    <input type="text" name="nm_nom_usu" class="form-control" id="inputNome" placeholder="Nome Completo" value="<?php echo $this->escapeHtml($this->form['nm_nom_usu']); ?>">
                </div>
            </div>

            <div class="form-group">
                <label for="inputLogin" class="col-lg-3 col-md-3 control-label">Login:</label>
                <div class="col-lg-9  col-md-9">
                    <input type="text" name="nm_usu_nom" class="form-control" id="inputLogin" placeholder="Digite seu login" value="<?php echo $this->escapeHtml($this->form['nm_usu_nom']); ?>">
                </div>
            </div>

            <div class="form-group">
                <label for="inputEmail" class="col-lg-3 col-md-3 control-label">E-Mail:</label>
                <div class="col-lg-9  col-md-9">
                    <input type="text" name="nm_eml_usu" class="form-control" id="inputEmail" placeholder="Digite seu e-mail" value="<?php echo $this->escapeHtml($this->form['nm_eml_usu']); ?>">
                </div>
            </div>
        </div>
        <div class="panel-footer">
            <input type="hidden" name="id" value="<?php echo $this->id; ?>">
            <button type="submit" class="btn btn-primary">Atualizar Usuário</button>
            <a href="<?php echo $this->url('usuarios'); ?>" class="btn btn-default">Voltar</a>
        </div>
    </form>
</div>